[workspace]
members = ["app","migration","infra"]
resolver = "3"

[workspace.dependencies]
tokio = "1"
clap = "4"
axum = "0.8.6"
anyhow = "1"
dotenvy = "0.15.7"
sentry = "0.45.0"
tower = "0.5.2"
tower-http= "0.6.2"
sea-orm ="2.0.0-rc.15"
tracing = "0.1"
tracing-subscriber = "0.3"
