[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
